services:
  redis:
    image: redis:7-alpine
    container_name: synapse-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    networks:
      - synapse_network

  postgres:
    image: postgres:15-alpine
    container_name: synapse-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=synapsegrid
      - POSTGRES_USER=synapse
      - POSTGRES_PASSWORD=synapse123
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - synapse_network

  gateway:
    build:
      context: .
      dockerfile: services/gateway/Dockerfile
    container_name: synapse-gateway
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=postgres
    depends_on:
      - redis
      - postgres
    networks:
      - synapse_network

  dispatcher:
    build:
      context: .
      dockerfile: services/dispatcher/Dockerfile
    container_name: synapse-dispatcher
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - synapse_network

  aggregator:
    build:
      context: .
      dockerfile: services/aggregator/Dockerfile
    container_name: synapse-aggregator
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - synapse_network

  node1:
    build:
      context: .
      dockerfile: services/node/Dockerfile
    container_name: synapse-node-1
    environment:
      - NODE_ID=node-001
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - synapse_network

  dashboard:
    build:
      context: .
      dockerfile: services/dashboard/Dockerfile
    container_name: synapse-dashboard
    ports:
      - "3000:3000"
    networks:
      - synapse_network

  prometheus:
    image: prom/prometheus:latest
    container_name: synapse-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - synapse_network

  grafana:
    image: grafana/grafana:latest
    container_name: synapse-grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - synapse_network

volumes:
  postgres_data:
  prometheus_data:
  grafana_data:

networks:
  synapse_network:
    driver: bridge
