.PHONY: help build start stop logs clean

help:
	@echo "Commands:"
	@echo "  make build  - Build all services"
	@echo "  make start  - Start all services"
	@echo "  make stop   - Stop all services"
	@echo "  make logs   - View logs"
	@echo "  make clean  - Clean everything"

build:
	docker-compose build

start:
	docker-compose up -d

stop:
	docker-compose down

logs:
	docker-compose logs -f

clean:
	docker-compose down -v
	docker system prune -af
