global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'synapse-services'
    static_configs:
      - targets: 
          - 'gateway:8080'
          - 'dispatcher:8001'
          - 'aggregator:8002'
          - 'node:8003'
